export const info =[
    {
        id:1,
        image:"https://media.tacdn.com/media/attractions-splice-spp-674x446/06/6b/81/d7.jpg",
        description:"Discover Milestii Mici, the largest underground wine cellar in the world, located in the commune of Milestii Mici just 18km from Chisinau, the country’s capital,Stretching for 250 km, of which only 120 km are currently in use, the Milestii Mici cellar complex is also the largest in the world. In 2007 Milestii Mici wine cellars were noted in Guinness World Records 2007 Yearbook for having the largest (2 million) wine collections in the world.The wine collection consists of over 2 million bottles. The grapes collected from the wineyards around Milestii Mici village are of a special quality. The wine made out of these grapes has a rich and noble taste which is then stored  in the stone subways for many years.The tunnels were created by excavating limestone blocks to build Chisinau. It was converted into an underground wine cellar in 1969. The natural limestone helps to maintain a constant temperature of 12-14 C (54-57 F) and humidity of 97-98%, creating optimal conditions for storing wine. Most of the wine is stored in huge oak casks – made with Crimean or Krasnodar oak – that vary in size from 600 to 2,000 dal. The largest are big enough to hold a small car. The tunnels are named after the wines kept there.The Milestii Mici Golden Collection of wines, with wines dating back to 1969, is the pride of the cellar. The most valuable items of this collection were produced in 1973-74; they are now exported exclusively to Japan. The wines stored here are made from grapes harvested in various years, beginning with 1969. The wines were produced in keeping with old Moldovan traditions. Today, the winery produces wines following new, modern standards.In the centre of the cellar complex you will find a large restaurant and tasting complex. The tasting halls are luxuriously decorated, accented by water, stone, and wood features. The walls are made from natural sea shell rock, skillfully illuminated. The cellar also has mosaic ponds with goldfish, nice sculptures, and beautiful stained-glass windows.Visitors need their own vehicle for an hour tour with an expert guide. The tour weaves past a natural underwater cascade, the most prized vintages, and into a tasting room some 200 feet underground. Guests can taste a range of wines (dry, semi-dry, and sweet wines).",
        showMore:false
    },
    {
        id:2,
        image:"https://img.atlasobscura.com/pdfGSr4s2mq2tNeDjMuKRMXOM9ItRAMjJtMJxe4F1Dc/rt:fit/w:1200/q:81/sm:1/scp:1/ar:1/aHR0cHM6Ly9hdGxh/cy1kZXYuczMuYW1h/em9uYXdzLmNvbS91/cGxvYWRzL3BsYWNl/X2ltYWdlcy85Nzg0/YmI3ZWM5MjY3YWE1/NzNiNWFjZTMwNzA3/MmU0ZmMzMjc1MDA4/LmpwZw.jpg",
        description:"Discover Milestii Mici, the largest underground wine cellar in the world, located in the commune of Milestii Mici just 18km from Chisinau, the country’s capital,Stretching for 250 km, of which only 120 km are currently in use, the Milestii Mici cellar complex is also the largest in the world. In 2007 Milestii Mici wine cellars were noted in Guinness World Records 2007 Yearbook for having the largest (2 million) wine collections in the world.The wine collection consists of over 2 million bottles. The grapes collected from the wineyards around Milestii Mici village are of a special quality. The wine made out of these grapes has a rich and noble taste which is then stored  in the stone subways for many years.The tunnels were created by excavating limestone blocks to build Chisinau. It was converted into an underground wine cellar in 1969. The natural limestone helps to maintain a constant temperature of 12-14 C (54-57 F) and humidity of 97-98%, creating optimal conditions for storing wine. Most of the wine is stored in huge oak casks – made with Crimean or Krasnodar oak – that vary in size from 600 to 2,000 dal. The largest are big enough to hold a small car. The tunnels are named after the wines kept there.The Milestii Mici Golden Collection of wines, with wines dating back to 1969, is the pride of the cellar. The most valuable items of this collection were produced in 1973-74; they are now exported exclusively to Japan. The wines stored here are made from grapes harvested in various years, beginning with 1969. The wines were produced in keeping with old Moldovan traditions. Today, the winery produces wines following new, modern standards.In the centre of the cellar complex you will find a large restaurant and tasting complex. The tasting halls are luxuriously decorated, accented by water, stone, and wood features. The walls are made from natural sea shell rock, skillfully illuminated. The cellar also has mosaic ponds with goldfish, nice sculptures, and beautiful stained-glass windows.Visitors need their own vehicle for an hour tour with an expert guide. The tour weaves past a natural underwater cascade, the most prized vintages, and into a tasting room some 200 feet underground. Guests can taste a range of wines (dry, semi-dry, and sweet wines).",
        showMore:false
    },
    {
        id:3,
        image:"https://img.atlasobscura.com/BCTamknmvxBG2lq2kzYkDnF1KtEXa1lTA5_jSvHUqjE/rt:fit/w:1200/q:81/sm:1/scp:1/ar:1/aHR0cHM6Ly9hdGxh/cy1kZXYuczMuYW1h/em9uYXdzLmNvbS91/cGxvYWRzL3BsYWNl/X2ltYWdlcy82MTE3/YzEyYjA0ZWY0YzQw/NzBjNmIxNTBlZTZl/ZWQwYmU0MjhiOGQ1/LmpwZw.jpg",
        description:"Discover Milestii Mici, the largest underground wine cellar in the world, located in the commune of Milestii Mici just 18km from Chisinau, the country’s capital,Stretching for 250 km, of which only 120 km are currently in use, the Milestii Mici cellar complex is also the largest in the world. In 2007 Milestii Mici wine cellars were noted in Guinness World Records 2007 Yearbook for having the largest (2 million) wine collections in the world.The wine collection consists of over 2 million bottles. The grapes collected from the wineyards around Milestii Mici village are of a special quality. The wine made out of these grapes has a rich and noble taste which is then stored  in the stone subways for many years.The tunnels were created by excavating limestone blocks to build Chisinau. It was converted into an underground wine cellar in 1969. The natural limestone helps to maintain a constant temperature of 12-14 C (54-57 F) and humidity of 97-98%, creating optimal conditions for storing wine. Most of the wine is stored in huge oak casks – made with Crimean or Krasnodar oak – that vary in size from 600 to 2,000 dal. The largest are big enough to hold a small car. The tunnels are named after the wines kept there.The Milestii Mici Golden Collection of wines, with wines dating back to 1969, is the pride of the cellar. The most valuable items of this collection were produced in 1973-74; they are now exported exclusively to Japan. The wines stored here are made from grapes harvested in various years, beginning with 1969. The wines were produced in keeping with old Moldovan traditions. Today, the winery produces wines following new, modern standards.In the centre of the cellar complex you will find a large restaurant and tasting complex. The tasting halls are luxuriously decorated, accented by water, stone, and wood features. The walls are made from natural sea shell rock, skillfully illuminated. The cellar also has mosaic ponds with goldfish, nice sculptures, and beautiful stained-glass windows.Visitors need their own vehicle for an hour tour with an expert guide. The tour weaves past a natural underwater cascade, the most prized vintages, and into a tasting room some 200 feet underground. Guests can taste a range of wines (dry, semi-dry, and sweet wines).",
        showMore:false
    },
    {
        id:4,
        image:"https://media.gettyimages.com/photos/galery-of-oak-barrels-with-wine-at-milestii-mici-wineyard-25-kms-picture-id71932964?k=20&m=71932964&s=612x612&w=0&h=JzI9J9YWW0TCWeWYHXUTcYFkKzdfJoUb9PWZH83X98A=",
        description:"Discover Milestii Mici, the largest underground wine cellar in the world, located in the commune of Milestii Mici just 18km from Chisinau, the country’s capital,Stretching for 250 km, of which only 120 km are currently in use, the Milestii Mici cellar complex is also the largest in the world. In 2007 Milestii Mici wine cellars were noted in Guinness World Records 2007 Yearbook for having the largest (2 million) wine collections in the world.The wine collection consists of over 2 million bottles. The grapes collected from the wineyards around Milestii Mici village are of a special quality. The wine made out of these grapes has a rich and noble taste which is then stored  in the stone subways for many years.The tunnels were created by excavating limestone blocks to build Chisinau. It was converted into an underground wine cellar in 1969. The natural limestone helps to maintain a constant temperature of 12-14 C (54-57 F) and humidity of 97-98%, creating optimal conditions for storing wine. Most of the wine is stored in huge oak casks – made with Crimean or Krasnodar oak – that vary in size from 600 to 2,000 dal. The largest are big enough to hold a small car. The tunnels are named after the wines kept there.The Milestii Mici Golden Collection of wines, with wines dating back to 1969, is the pride of the cellar. The most valuable items of this collection were produced in 1973-74; they are now exported exclusively to Japan. The wines stored here are made from grapes harvested in various years, beginning with 1969. The wines were produced in keeping with old Moldovan traditions. Today, the winery produces wines following new, modern standards.In the centre of the cellar complex you will find a large restaurant and tasting complex. The tasting halls are luxuriously decorated, accented by water, stone, and wood features. The walls are made from natural sea shell rock, skillfully illuminated. The cellar also has mosaic ponds with goldfish, nice sculptures, and beautiful stained-glass windows.Visitors need their own vehicle for an hour tour with an expert guide. The tour weaves past a natural underwater cascade, the most prized vintages, and into a tasting room some 200 feet underground. Guests can taste a range of wines (dry, semi-dry, and sweet wines).",
        showMore:false
    },
    {
        id:5,
        image:"https://media.gettyimages.com/photos/wine-cellar-milestii-mici-in-moldova-picture-id555461605?k=20&m=555461605&s=612x612&w=0&h=ZcSebmh2_1Gi22rQ5nBM6bTHNLyaoBgwdEVL6J2Rof4=",
        description:"Discover Milestii Mici, the largest underground wine cellar in the world, located in the commune of Milestii Mici just 18km from Chisinau, the country’s capital,Stretching for 250 km, of which only 120 km are currently in use, the Milestii Mici cellar complex is also the largest in the world. In 2007 Milestii Mici wine cellars were noted in Guinness World Records 2007 Yearbook for having the largest (2 million) wine collections in the world.The wine collection consists of over 2 million bottles. The grapes collected from the wineyards around Milestii Mici village are of a special quality. The wine made out of these grapes has a rich and noble taste which is then stored  in the stone subways for many years.The tunnels were created by excavating limestone blocks to build Chisinau. It was converted into an underground wine cellar in 1969. The natural limestone helps to maintain a constant temperature of 12-14 C (54-57 F) and humidity of 97-98%, creating optimal conditions for storing wine. Most of the wine is stored in huge oak casks – made with Crimean or Krasnodar oak – that vary in size from 600 to 2,000 dal. The largest are big enough to hold a small car. The tunnels are named after the wines kept there.The Milestii Mici Golden Collection of wines, with wines dating back to 1969, is the pride of the cellar. The most valuable items of this collection were produced in 1973-74; they are now exported exclusively to Japan. The wines stored here are made from grapes harvested in various years, beginning with 1969. The wines were produced in keeping with old Moldovan traditions. Today, the winery produces wines following new, modern standards.In the centre of the cellar complex you will find a large restaurant and tasting complex. The tasting halls are luxuriously decorated, accented by water, stone, and wood features. The walls are made from natural sea shell rock, skillfully illuminated. The cellar also has mosaic ponds with goldfish, nice sculptures, and beautiful stained-glass windows.Visitors need their own vehicle for an hour tour with an expert guide. The tour weaves past a natural underwater cascade, the most prized vintages, and into a tasting room some 200 feet underground. Guests can taste a range of wines (dry, semi-dry, and sweet wines).",
        showMore:false
    },
    {
        id:6,
        image:"https://media.gettyimages.com/photos/full-frame-shot-of-stone-wall-picture-id1234566818?k=20&m=1234566818&s=612x612&w=0&h=7jSf8JZezqB24wG0CaWIsTIl5lqibSFALbv71hQaLqU=",
        description:"Discover Milestii Mici, the largest underground wine cellar in the world, located in the commune of Milestii Mici just 18km from Chisinau, the country’s capital,Stretching for 250 km, of which only 120 km are currently in use, the Milestii Mici cellar complex is also the largest in the world. In 2007 Milestii Mici wine cellars were noted in Guinness World Records 2007 Yearbook for having the largest (2 million) wine collections in the world.The wine collection consists of over 2 million bottles. The grapes collected from the wineyards around Milestii Mici village are of a special quality. The wine made out of these grapes has a rich and noble taste which is then stored  in the stone subways for many years.The tunnels were created by excavating limestone blocks to build Chisinau. It was converted into an underground wine cellar in 1969. The natural limestone helps to maintain a constant temperature of 12-14 C (54-57 F) and humidity of 97-98%, creating optimal conditions for storing wine. Most of the wine is stored in huge oak casks – made with Crimean or Krasnodar oak – that vary in size from 600 to 2,000 dal. The largest are big enough to hold a small car. The tunnels are named after the wines kept there.The Milestii Mici Golden Collection of wines, with wines dating back to 1969, is the pride of the cellar. The most valuable items of this collection were produced in 1973-74; they are now exported exclusively to Japan. The wines stored here are made from grapes harvested in various years, beginning with 1969. The wines were produced in keeping with old Moldovan traditions. Today, the winery produces wines following new, modern standards.In the centre of the cellar complex you will find a large restaurant and tasting complex. The tasting halls are luxuriously decorated, accented by water, stone, and wood features. The walls are made from natural sea shell rock, skillfully illuminated. The cellar also has mosaic ponds with goldfish, nice sculptures, and beautiful stained-glass windows.Visitors need their own vehicle for an hour tour with an expert guide. The tour weaves past a natural underwater cascade, the most prized vintages, and into a tasting room some 200 feet underground. Guests can taste a range of wines (dry, semi-dry, and sweet wines).",
        showMore:false
    },
    {
        id:7,
        image:"https://media.gettyimages.com/photos/july-2021-russia-chisinau-a-decoration-made-of-wine-glasses-stands-on-picture-id1234582808?k=20&m=1234582808&s=612x612&w=0&h=mCk72Ew1uUBPOJSQ01p3p77HBoJl1f0nKru7BLlJtck=",
        description:"Discover Milestii Mici, the largest underground wine cellar in the world, located in the commune of Milestii Mici just 18km from Chisinau, the country’s capital,Stretching for 250 km, of which only 120 km are currently in use, the Milestii Mici cellar complex is also the largest in the world. In 2007 Milestii Mici wine cellars were noted in Guinness World Records 2007 Yearbook for having the largest (2 million) wine collections in the world.The wine collection consists of over 2 million bottles. The grapes collected from the wineyards around Milestii Mici village are of a special quality. The wine made out of these grapes has a rich and noble taste which is then stored  in the stone subways for many years.The tunnels were created by excavating limestone blocks to build Chisinau. It was converted into an underground wine cellar in 1969. The natural limestone helps to maintain a constant temperature of 12-14 C (54-57 F) and humidity of 97-98%, creating optimal conditions for storing wine. Most of the wine is stored in huge oak casks – made with Crimean or Krasnodar oak – that vary in size from 600 to 2,000 dal. The largest are big enough to hold a small car. The tunnels are named after the wines kept there.The Milestii Mici Golden Collection of wines, with wines dating back to 1969, is the pride of the cellar. The most valuable items of this collection were produced in 1973-74; they are now exported exclusively to Japan. The wines stored here are made from grapes harvested in various years, beginning with 1969. The wines were produced in keeping with old Moldovan traditions. Today, the winery produces wines following new, modern standards.In the centre of the cellar complex you will find a large restaurant and tasting complex. The tasting halls are luxuriously decorated, accented by water, stone, and wood features. The walls are made from natural sea shell rock, skillfully illuminated. The cellar also has mosaic ponds with goldfish, nice sculptures, and beautiful stained-glass windows.Visitors need their own vehicle for an hour tour with an expert guide. The tour weaves past a natural underwater cascade, the most prized vintages, and into a tasting room some 200 feet underground. Guests can taste a range of wines (dry, semi-dry, and sweet wines).",
        showMore:false
    },
    {
        id:8,
        image:"https://wineofmoldova.com/wp-content/uploads/2020/12/gallery-image-2-milestii-mici.png",
        description:"Discover Milestii Mici, the largest underground wine cellar in the world, located in the commune of Milestii Mici just 18km from Chisinau, the country’s capital,Stretching for 250 km, of which only 120 km are currently in use, the Milestii Mici cellar complex is also the largest in the world. In 2007 Milestii Mici wine cellars were noted in Guinness World Records 2007 Yearbook for having the largest (2 million) wine collections in the world.The wine collection consists of over 2 million bottles. The grapes collected from the wineyards around Milestii Mici village are of a special quality. The wine made out of these grapes has a rich and noble taste which is then stored  in the stone subways for many years.The tunnels were created by excavating limestone blocks to build Chisinau. It was converted into an underground wine cellar in 1969. The natural limestone helps to maintain a constant temperature of 12-14 C (54-57 F) and humidity of 97-98%, creating optimal conditions for storing wine. Most of the wine is stored in huge oak casks – made with Crimean or Krasnodar oak – that vary in size from 600 to 2,000 dal. The largest are big enough to hold a small car. The tunnels are named after the wines kept there.The Milestii Mici Golden Collection of wines, with wines dating back to 1969, is the pride of the cellar. The most valuable items of this collection were produced in 1973-74; they are now exported exclusively to Japan. The wines stored here are made from grapes harvested in various years, beginning with 1969. The wines were produced in keeping with old Moldovan traditions. Today, the winery produces wines following new, modern standards.In the centre of the cellar complex you will find a large restaurant and tasting complex. The tasting halls are luxuriously decorated, accented by water, stone, and wood features. The walls are made from natural sea shell rock, skillfully illuminated. The cellar also has mosaic ponds with goldfish, nice sculptures, and beautiful stained-glass windows.Visitors need their own vehicle for an hour tour with an expert guide. The tour weaves past a natural underwater cascade, the most prized vintages, and into a tasting room some 200 feet underground. Guests can taste a range of wines (dry, semi-dry, and sweet wines).",
        showMore:false
    },
    {
        id:9,
        image:"https://media.tacdn.com/media/attractions-splice-spp-674x446/07/74/80/a4.jpg",
        description:"Discover Milestii Mici, the largest underground wine cellar in the world, located in the commune of Milestii Mici just 18km from Chisinau, the country’s capital,Stretching for 250 km, of which only 120 km are currently in use, the Milestii Mici cellar complex is also the largest in the world. In 2007 Milestii Mici wine cellars were noted in Guinness World Records 2007 Yearbook for having the largest (2 million) wine collections in the world.The wine collection consists of over 2 million bottles. The grapes collected from the wineyards around Milestii Mici village are of a special quality. The wine made out of these grapes has a rich and noble taste which is then stored  in the stone subways for many years.The tunnels were created by excavating limestone blocks to build Chisinau. It was converted into an underground wine cellar in 1969. The natural limestone helps to maintain a constant temperature of 12-14 C (54-57 F) and humidity of 97-98%, creating optimal conditions for storing wine. Most of the wine is stored in huge oak casks – made with Crimean or Krasnodar oak – that vary in size from 600 to 2,000 dal. The largest are big enough to hold a small car. The tunnels are named after the wines kept there.The Milestii Mici Golden Collection of wines, with wines dating back to 1969, is the pride of the cellar. The most valuable items of this collection were produced in 1973-74; they are now exported exclusively to Japan. The wines stored here are made from grapes harvested in various years, beginning with 1969. The wines were produced in keeping with old Moldovan traditions. Today, the winery produces wines following new, modern standards.In the centre of the cellar complex you will find a large restaurant and tasting complex. The tasting halls are luxuriously decorated, accented by water, stone, and wood features. The walls are made from natural sea shell rock, skillfully illuminated. The cellar also has mosaic ponds with goldfish, nice sculptures, and beautiful stained-glass windows.Visitors need their own vehicle for an hour tour with an expert guide. The tour weaves past a natural underwater cascade, the most prized vintages, and into a tasting room some 200 feet underground. Guests can taste a range of wines (dry, semi-dry, and sweet wines).",
        showMore:false
    },
    {
        id:10,
        image:"https://media.tacdn.com/media/attractions-splice-spp-674x446/07/74/80/aa.jpg",
        description:"Discover Milestii Mici, the largest underground wine cellar in the world, located in the commune of Milestii Mici just 18km from Chisinau, the country’s capital,Stretching for 250 km, of which only 120 km are currently in use, the Milestii Mici cellar complex is also the largest in the world. In 2007 Milestii Mici wine cellars were noted in Guinness World Records 2007 Yearbook for having the largest (2 million) wine collections in the world.The wine collection consists of over 2 million bottles. The grapes collected from the wineyards around Milestii Mici village are of a special quality. The wine made out of these grapes has a rich and noble taste which is then stored  in the stone subways for many years.The tunnels were created by excavating limestone blocks to build Chisinau. It was converted into an underground wine cellar in 1969. The natural limestone helps to maintain a constant temperature of 12-14 C (54-57 F) and humidity of 97-98%, creating optimal conditions for storing wine. Most of the wine is stored in huge oak casks – made with Crimean or Krasnodar oak – that vary in size from 600 to 2,000 dal. The largest are big enough to hold a small car. The tunnels are named after the wines kept there.The Milestii Mici Golden Collection of wines, with wines dating back to 1969, is the pride of the cellar. The most valuable items of this collection were produced in 1973-74; they are now exported exclusively to Japan. The wines stored here are made from grapes harvested in various years, beginning with 1969. The wines were produced in keeping with old Moldovan traditions. Today, the winery produces wines following new, modern standards.In the centre of the cellar complex you will find a large restaurant and tasting complex. The tasting halls are luxuriously decorated, accented by water, stone, and wood features. The walls are made from natural sea shell rock, skillfully illuminated. The cellar also has mosaic ponds with goldfish, nice sculptures, and beautiful stained-glass windows.Visitors need their own vehicle for an hour tour with an expert guide. The tour weaves past a natural underwater cascade, the most prized vintages, and into a tasting room some 200 feet underground. Guests can taste a range of wines (dry, semi-dry, and sweet wines).",
        showMore:false
    }

]